#! /usr/bin/env php
<?php

require __DIR__ . '/bootstrap.php';

/**
 * Basic application configurations.
 */
$config = require __DIR__ . '/config/frontend/app.php';

/**
 * Loading routes definitions.
 */
$config['routes'] = require __DIR__ . '/config/frontend/routes.php';

/**
 * Loading application service definitions.
 */
$config['services'] = require __DIR__ . '/config/frontend/services.php';

$app = new \blink\core\Application($config);
$status = $app->handleConsole(
    new Symfony\Component\Console\Input\ArgvInput,
    new Symfony\Component\Console\Output\ConsoleOutput
);
exit($status);
